config/routes.rb
Rails.application.routes.draw do

  resources :reviews
  resources:books
  root "books#index"
 
end

app/models/book.rb
class Book < ActiveRecord::Base
    has_many :reviews
    validates :name,presence:true,length:{ maximum:20 }
    validates :price,presence:true
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to:book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book,only:[:show,:edit,:update,:destroy]
  def index
    @books = Book.all
  end
  
  def show
    #@book = Book.find(params[:id])
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.valid?
    @book.save
    # リダイレクト
    redirect_to books_path
  else
    flash[:alert]= @book.errors.full_messages
    render:new
  end
  
  def edit
    #@book = Book.find(params[:id])
  end
  end
  
  def update
    #@book = Book.find(params[:id])
    @book.update(book_params)
    
    # リダイレクト
    redirect_to book_path
  end
  
  def destroy
    #@book = Book.fine(params[:id])
    @book.destroy
    
    redirect_to books_path
    
  end
  
  private
  def set_book
    @book = Book.find(params[:id])
  end
  
   private
  def book_params
    params.require(:book).permit(:name,:price,:publish,:publish_date)
  end
  
  
  
  
  
  
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
      #  format.html { redirect_to @review, notice: 'Review was successfully created.' }
      format.html { redirect_to controller: :books,
                                action: :show,
                                id:@review.book.id,
                                notice:"Review was successfully created!!"
      }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:book_id, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_new_review.html.erb
<%= form_for(review) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :book_id %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<%= form_for @book do |f| %>
  <div>
    書籍名: <%= f.text_field :name %>
  </div>
  <div>
    価格: <%= f.number_field :price %>
  </div>
  <div>
    出版社: <%= f.text_field :publish %>
  </div>
  <div>
    刊行日: <%= f.date_field :publish_date %>
  </div>
  <%= f.submit "更新" %>
<% end %>

app/views/books/index.html.erb
<h1>書籍一覧</h1>
<% @books.each do |book| %>
    <ul>
    <li>
        <%= book.name %>
        <%= link_to '詳細',book_path(book) %>
    </li>
    </ul>
<% end %>
    <p><%= link_to '新規追加',new_book_path %></p>
    

app/views/books/new.html.erb
<% flash.each do |key,value| %>
  <%= content_tag(:div,value,class:"#{key}") %>
<% end %>
<%= form_for @book do |f| %>
  <div>
    書籍名: <br><%= f.text_field :name %>
  </div>
  <div>
    価格: <br><%= f.number_field :price %>
  </div>
  <div>
    出版社: <br><%= f.text_field :publish %>
  </div>
  <div>
    刊行日: <br><%= f.date_field :publish_date %>
  </div>
  <%= f.submit "追加" %>
<% end %>

app/views/books/show.html.erb
<h2>書籍詳細</h2>
<p>ID:<%= @book.id %></p>
<p>書籍名:<%= @book.name %></p>
<p>価格:<%= @book.price %></p>
<p>出版社:<%= @book.publish %></p>
<p>刊行日:<%= @book.publish_date %></p>
<hr>
<%= link_to '編集する',edit_book_path(@book) %>
<%= link_to '削除する',book_path(@book),method: :delete %>

<h3>レビュー一覧</h3>
<% @book.reviews.each do |review| %>
    <li><%= review.body %></li>
<% end %>

<h3>レビュー投稿</h3>
<%= render partial: "new_review" ,locals:{ review: Review.new(book_id:@book.id)}%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookShelfV2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_id %><br>
    <%= f.number_field :book_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.book_id %></td>
        <td><%= review.body %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @review.book_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>